=== ONSdigital/census31-eq-questionnaire-runner-interface-definitions/schemas/launch_v2.json
{
  "$id": "launch_v2.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ONS EQ Launch Schema v2",
  "type": "object",
  "properties": {
    "account_service_url": {
      "$ref": "common/definitions.json#/account_service_url"
    },
    "account_service_log_out_url": {
      "$ref": "common/definitions.json#/account_service_log_out_url"
    },
    "case_id": {
      "$ref": "common/definitions.json#/case_id"
    },
    "channel": {
      "$ref": "common/definitions.json#/channel"
    },
    "collection_exercise_sid": {
      "$ref": "common/definitions.json#/collection_exercise_sid"
    },
    "exp": {
      "description": "JWT Issued At claim, see https://tools.ietf.org/html/rfc7519#section-4.1",
      "type": "integer"
    },
    "iat": {
      "description": "JWT Expiration Time claim, see https://tools.ietf.org/html/rfc7519#section-4.1",
      "type": "integer"
    },
    "jti": {
      "$ref": "common/definitions.json#/jti"
    },
    "language_code": {
      "$ref": "common/definitions.json#/launch_language_code"
    },
    "region_code": {
      "$ref": "common/definitions.json#/region_code"
    },
    "response_expires_at": {
      "$ref": "common/definitions.json#/response_expires_at"
    },
    "response_id": {
      "$ref": "common/definitions.json#/response_id"
    },
    "schema_name": {
      "$ref": "common/definitions.json#/schema_name"
    },
    "schema_url": {
      "$ref": "common/definitions.json#/schema_url"
    },
    "survey_metadata": {
      "$ref": "common/survey_metadata.json#/survey_metadata"
    },
    "tx_id": {
      "$ref": "common/definitions.json#/tx_id"
    },
    "version": {
      "$ref": "common/definitions.json#/payload_version_v2"
    },
    "survey": {
      "$ref": "common/definitions.json#/survey"
    },
    "eq_id": {
      "$ref": "common/definitions.json#/eq_id"
    }
  },
  "required": [
    "exp",
    "iat",
    "jti",
    "tx_id",
    "version",
    "account_service_url",
    "case_id",
    "collection_exercise_sid",
    "response_id",
    "response_expires_at"
  ],
  "additionalProperties": false,
  "oneOf": [
    {
      "required": ["schema_name"]
    },
    {
      "required": ["schema_url"]
    }
  ]
}

=== ONSdigital/census31-eq-questionnaire-runner-interface-definitions/examples/rm_to_eq_runner/payload_v2/launch_jwt_census.json
{
  "account_service_log_out_url": "http://localhost:8000/logout",
  "account_service_url": "http://localhost:8000",
  "case_id": "f48e8790-f591-4086-9f6d-98c8642d96cb",
  "channel": "rh",
  "collection_exercise_sid": "77d00da0-9245-40a3-9219-a9f860066167",
  "eq_id": "census",
  "exp": 1781701146,
  "iat": 1781693946,
  "jti": "1c6eff87-cc03-425b-9bd4-f4c81596cd86",
  "language_code": "en",
  "region_code": "GB-ENG",
  "response_expires_at": "2027-06-22T13:23:39+00:00",
  "response_id": "1929",
  "schema_name": "census_household_gb_eng",
  "survey": "CENSUS",
  "survey_metadata": {
    "data": {
      "case_type": "HH",
      "display_address": "15 Credibility Street, Bristol, BS7 8ES",
      "form_type": "H",
      "period_id": "2027",
      "ru_ref": "uprn:00001",
      "user_id": "UNKNOWN"
    },
    "receipting_keys": ["questionnaire_id"]
  },
  "tx_id": "7e916adc-1f36-4f1e-81f9-57a4ab4ad183",
  "version": "v2"
}
