=== ONSdigital/census31-eq-questionnaire-runner-interface-definitions/schemas/submission_v2.json
{
  "$id": "submission_v2.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "ONS EQ Submission Schema v2",
  "properties": {
    "case_id": {
      "$ref": "common/definitions.json#/case_id"
    },
    "channel": {
      "$ref": "common/definitions.json#/channel"
    },
    "collection_exercise_sid": {
      "$ref": "common/definitions.json#/collection_exercise_sid"
    },
    "data": {
      "description": "This is conditionally defined in the schemas below."
    },
    "data_version": {
      "$ref": "common/definitions.json#/data_version"
    },
    "flushed": {
      "$ref": "common/definitions.json#/flushed"
    },
    "launch_language_code": {
      "$ref": "common/definitions.json#/launch_language_code"
    },
    "period_id": {
      "$ref": "common/definitions.json#/period_id"
    },
    "origin": {
      "$ref": "common/definitions.json#/origin"
    },
    "schema": {
      "$ref": "common/definitions.json#/schema"
    },
    "schema_name": {
      "$ref": "common/definitions.json#/schema_name"
    },
    "schema_url": {
      "$ref": "common/definitions.json#/schema_url"
    },
    "started_at": {
      "$ref": "common/definitions.json#/started_at"
    },
    "submission_language_code": {
      "$ref": "common/definitions.json#/submission_language_code"
    },
    "submitted_at": {
      "$ref": "common/definitions.json#/submitted_at"
    },
    "survey_metadata": {
      "$ref": "common/survey_metadata.json#/survey_metadata"
    },
    "tx_id": {
      "$ref": "common/definitions.json#/tx_id"
    },
    "type": {
      "$ref": "common/definitions.json#/submission_type"
    },
    "version": {
      "$ref": "common/definitions.json#/payload_version_v2"
    },
    "survey_id": {
      "$ref": "common/definitions.json#/survey_id"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "allOf": [
    {
      "if": {
        "properties": { "type": { "const": "uk.gov.ons.edc.eq:feedback" } }
      },
      "then": {
        "properties": {
          "data": {
            "oneOf": [
              { "$ref": "common/response_data.json#/feedback_response" },
              { "$ref": "common/response_data.json#/feedback_response_legacy" }
            ]
          }
        }
      },
      "else": {
        "if": {
          "properties": {
            "type": { "const": "uk.gov.ons.edc.eq:user_research" }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "common/response_data.json#/user_research_response"
            }
          }
        },
        "else": {
          "if": {
            "properties": { "data_version": { "const": "0.0.3" } }
          },
          "then": {
            "properties": {
              "data": {
                "$ref": "common/response_data.json#/survey_response_0_0_3"
              }
            }
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "flushed": {
            "const": false
          }
        }
      },
      "then": {
        "required": ["submission_language_code"]
      }
    }
  ],
  "required": [
    "tx_id",
    "type",
    "version",
    "data_version",
    "origin",
    "flushed",
    "submitted_at",
    "launch_language_code",
    "collection_exercise_sid",
    "case_id",
    "survey_metadata",
    "data",
    "schema",
    "schema_name"
  ]
}

=== ONSdigital/census31-eq-questionnaire-runner-interface-definitions/examples/submission/payload_v2/feedback_0_0_3.json
{
  "tx_id": "7e916adc-1f36-4f1e-81f9-57a4ab4ad183",
  "type": "uk.gov.ons.edc.eq:feedback",
  "version": "v2",
  "data_version": "0.0.3",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2026-06-19T14:06:29.474909+00:00",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "77d00da0-9245-40a3-9219-a9f860066167",
  "period_id": "2027",
  "schema": {
    "survey": "CENSUS",
    "form_type": "H",
    "region_code": "GB-ENG"
  },
  "schema_name": "census_household_gb_eng",
  "case_id": "f48e8790-f591-4086-9f6d-98c8642d96cb",
  "survey_metadata": {
    "user_id": "UNKNOWN",
    "display_address": "15 Credibility Street, Bristol, BS7 8ES",
    "questionnaire_id": "1234567890",
    "case_type": "HH",
    "ru_ref": "uprn:00001"
  },
  "data": {
    "feedback_text": "The 2021 Census was fantastic! I hope you do it all again in 2027!",
    "feedback_type": "General feedback about this service",
    "feedback_count": "1"
  },
  "channel": "rh",
  "started_at": "2026-06-19T14:04:53.323989+00:00"
}
